/**
 * Niche Scenarios — configuração de negócio + cenários de conversa por nicho.
 * Usado pelos specs de integração live para validar cada vertical.
 */

import { NicheConfig } from './helpers/niche-seed-fixtures';

export interface NicheScenario {
  config: NicheConfig;
  companyName: string;
  welcomeQuestion: string;
  serviceQuestion: string;
  purchaseQuestion: string;
  schedulingQuestion: string;
  menuResetPhrase: string;
  expectedWelcomeSignals: string[];
  expectedServiceSignals: string[];
  expectedPurchaseSignals: string[];
  expectedSchedulingSignals: string[];
  hasScheduling: boolean;
  hasCommerce: boolean;
}

export const NICHE_SCENARIOS: NicheScenario[] = [
  {
    config: {
      businessType: 'BEAUTY',
      label: 'Estética & Beleza',
      description: 'Salão de beleza premium com 10 anos de experiência em cortes, coloração e tratamentos capilares.',
      services: 'Corte feminino R$80, Corte masculino R$50, Escova R$60, Coloração R$150, Hidratação R$90, Manicure R$40.',
    },
    companyName: 'Salão Glamour',
    welcomeQuestion: 'Oi, boa tarde!',
    serviceQuestion: 'Quais serviços vocês oferecem e quanto custa?',
    purchaseQuestion: 'Quero fazer uma coloração, como pago?',
    schedulingQuestion: 'Tem horário disponível para amanhã de manhã?',
    menuResetPhrase: 'voltar ao menu',
    expectedWelcomeSignals: ['bem-vind', 'ajudar', 'servico', 'agendar', 'horario'],
    expectedServiceSignals: ['corte', 'escova', 'coloracao', 'R$', 'preco'],
    expectedPurchaseSignals: ['pagamento', 'link', 'pagar', 'coloracao', 'R$150', 'agendar'],
    expectedSchedulingSignals: ['horario', 'disponivel', 'amanha', 'agenda', 'slot'],
    hasScheduling: true,
    hasCommerce: false,
  },
  {
    config: {
      businessType: 'FOOD',
      label: 'Alimentação & Restaurante',
      description: 'Restaurante japonês com delivery próprio. Cardápio variado com sushi, sashimi, temaki e pratos quentes.',
      services: 'Combo Sushi 20pcs R$59.90, Temaki Salmão R$28, Hot Roll 10pcs R$35, Yakisoba R$32, Delivery grátis acima R$80.',
    },
    companyName: 'Sushi Zen',
    welcomeQuestion: 'Oi, quero fazer um pedido',
    serviceQuestion: 'O que vocês tem no cardápio?',
    purchaseQuestion: 'Quero um combo sushi de 20 peças',
    schedulingQuestion: 'Qual o tempo de entrega?',
    menuResetPhrase: 'voltar',
    expectedWelcomeSignals: ['cardapio', 'pedido', 'delivery', 'menu', 'ajudar'],
    expectedServiceSignals: ['sushi', 'temaki', 'hot roll', 'yakisoba', 'R$'],
    expectedPurchaseSignals: ['combo', 'sushi', 'R$59', 'pedido', 'endereco', 'entrega', 'pagamento'],
    expectedSchedulingSignals: ['entrega', 'tempo', 'minutos', 'previsao'],
    hasScheduling: false,
    hasCommerce: true,
  },
  {
    config: {
      businessType: 'ECOMMERCE',
      label: 'E-commerce & Varejo',
      description: 'Loja de eletrônicos com entrega para todo Brasil. Fones, acessórios, cabos e gadgets.',
      services: 'Fone Bluetooth R$150, Fone com Fio R$40, Cabo USB-C R$25, Carregador Turbo R$89, Capa Celular R$35.',
    },
    companyName: 'TechStore',
    welcomeQuestion: 'Olá!',
    serviceQuestion: 'Quais produtos vocês vendem?',
    purchaseQuestion: 'Quero comprar um fone bluetooth',
    schedulingQuestion: 'Qual o prazo de entrega para São Paulo?',
    menuResetPhrase: 'menu',
    expectedWelcomeSignals: ['produto', 'loja', 'ajudar', 'catalogo', 'bem-vind'],
    expectedServiceSignals: ['fone', 'bluetooth', 'cabo', 'carregador', 'R$'],
    expectedPurchaseSignals: ['fone', 'bluetooth', 'R$150', 'carrinho', 'pagamento', 'endereco', 'link'],
    expectedSchedulingSignals: ['entrega', 'prazo', 'dia', 'frete'],
    hasScheduling: false,
    hasCommerce: true,
  },
  {
    config: {
      businessType: 'GYM',
      label: 'Academia & Fitness',
      description: 'Studio de pilates e funcional com aulas em grupo e personal trainer. Planos mensais e avulsos.',
      services: 'Plano Mensal R$180, Aula Avulsa R$45, Personal Trainer R$120/hora, Avaliação Física R$80.',
    },
    companyName: 'Studio FitLife',
    welcomeQuestion: 'Oi, quero informações',
    serviceQuestion: 'Quais planos vocês tem?',
    purchaseQuestion: 'Quero assinar o plano mensal',
    schedulingQuestion: 'Tem aula experimental disponível?',
    menuResetPhrase: 'inicio',
    expectedWelcomeSignals: ['plano', 'aula', 'ajudar', 'fitness', 'bem-vind'],
    expectedServiceSignals: ['plano', 'mensal', 'R$180', 'personal', 'avaliacao'],
    expectedPurchaseSignals: ['plano', 'mensal', 'R$180', 'pagamento', 'assinar', 'link'],
    expectedSchedulingSignals: ['aula', 'experimental', 'horario', 'disponivel', 'agenda'],
    hasScheduling: true,
    hasCommerce: false,
  },
  {
    config: {
      businessType: 'CLINIC',
      label: 'Clínica & Saúde',
      description: 'Clínica multidisciplinar com dermatologia, nutrição e psicologia. Atendimento particular e convênios.',
      services: 'Consulta Dermatologia R$250, Consulta Nutrição R$180, Psicologia R$200, Retorno R$120.',
    },
    companyName: 'Clínica Vida',
    welcomeQuestion: 'Boa tarde, preciso agendar uma consulta',
    serviceQuestion: 'Quais especialidades vocês atendem?',
    purchaseQuestion: 'Quanto custa uma consulta de dermatologia?',
    schedulingQuestion: 'Tem horário para dermatologia essa semana?',
    menuResetPhrase: 'voltar ao inicio',
    expectedWelcomeSignals: ['consulta', 'agendar', 'especialidade', 'ajudar', 'clinica'],
    expectedServiceSignals: ['dermatologia', 'nutricao', 'psicologia', 'consulta'],
    expectedPurchaseSignals: ['dermatologia', 'R$250', 'consulta', 'pagamento', 'agendar'],
    expectedSchedulingSignals: ['horario', 'disponivel', 'semana', 'agenda', 'consulta'],
    hasScheduling: true,
    hasCommerce: false,
  },
  {
    config: {
      businessType: 'EDUCATION',
      label: 'Educação & Cursos',
      description: 'Escola de idiomas com cursos de inglês, espanhol e francês. Turmas presenciais e online.',
      services: 'Inglês Básico R$299/mês, Inglês Avançado R$399/mês, Espanhol R$279/mês, Conversação R$199/mês.',
    },
    companyName: 'Idiomas Plus',
    welcomeQuestion: 'Oi, quero saber sobre os cursos',
    serviceQuestion: 'Quais cursos de inglês vocês oferecem?',
    purchaseQuestion: 'Quero me matricular no curso básico de inglês',
    schedulingQuestion: 'Quando começa a próxima turma?',
    menuResetPhrase: 'menu principal',
    expectedWelcomeSignals: ['curso', 'idioma', 'ingles', 'ajudar', 'matricula'],
    expectedServiceSignals: ['ingles', 'basico', 'avancado', 'R$', 'mes'],
    expectedPurchaseSignals: ['matricula', 'ingles', 'basico', 'R$299', 'pagamento', 'link'],
    expectedSchedulingSignals: ['turma', 'inicio', 'proxima', 'data', 'vagas'],
    hasScheduling: false,
    hasCommerce: false,
  },
  {
    config: {
      businessType: 'REAL_ESTATE',
      label: 'Imobiliária',
      description: 'Imobiliária com imóveis para venda e aluguel em São Paulo. Apartamentos, casas e salas comerciais.',
      services: 'Apartamento 2Q Moema R$650mil, Casa 3Q Pinheiros R$1.2mi, Sala Comercial Faria Lima R$8mil/mês, Studio Paulista R$450mil.',
    },
    companyName: 'SP Imóveis',
    welcomeQuestion: 'Oi, estou procurando um apartamento',
    serviceQuestion: 'Quais imóveis vocês tem disponíveis em Moema?',
    purchaseQuestion: 'Quero agendar uma visita no apartamento de Moema',
    schedulingQuestion: 'Tem disponibilidade para visita no sábado?',
    menuResetPhrase: 'voltar',
    expectedWelcomeSignals: ['imovel', 'apartamento', 'ajudar', 'regiao', 'busca'],
    expectedServiceSignals: ['moema', 'apartamento', 'quarto', 'R$', 'disponivel'],
    expectedPurchaseSignals: ['visita', 'agendar', 'moema', 'apartamento', 'horario'],
    expectedSchedulingSignals: ['sabado', 'visita', 'disponivel', 'horario', 'agenda'],
    hasScheduling: true,
    hasCommerce: false,
  },
  {
    config: {
      businessType: 'PET',
      label: 'Pet Shop',
      description: 'Pet shop completo com banho, tosa, veterinário e produtos. Atendimento com hora marcada.',
      services: 'Banho Pequeno R$50, Banho Grande R$80, Tosa Higiênica R$40, Consulta Vet R$150, Vacina R$90.',
    },
    companyName: 'PetHappy',
    welcomeQuestion: 'Oi, preciso agendar banho pro meu cachorro',
    serviceQuestion: 'Quais serviços vocês fazem para cachorro grande?',
    purchaseQuestion: 'Quanto custa banho e tosa para golden retriever?',
    schedulingQuestion: 'Tem horário para banho amanhã de manhã?',
    menuResetPhrase: 'menu',
    expectedWelcomeSignals: ['banho', 'pet', 'agendar', 'ajudar', 'servico'],
    expectedServiceSignals: ['banho', 'grande', 'R$80', 'tosa', 'veterinario'],
    expectedPurchaseSignals: ['banho', 'tosa', 'R$', 'pagamento', 'agendar'],
    expectedSchedulingSignals: ['horario', 'amanha', 'disponivel', 'manha', 'agenda'],
    hasScheduling: true,
    hasCommerce: false,
  },
  {
    config: {
      businessType: 'LAW',
      label: 'Advocacia',
      description: 'Escritório de advocacia especializado em direito trabalhista, civil e empresarial. Consultas online e presenciais.',
      services: 'Consulta Trabalhista R$300, Consulta Civil R$350, Consultoria Empresarial R$500/hora, Análise Contratual R$400.',
    },
    companyName: 'Advocacia Silva & Associados',
    welcomeQuestion: 'Boa tarde, preciso de um advogado',
    serviceQuestion: 'Vocês atendem questões trabalhistas?',
    purchaseQuestion: 'Quanto custa uma consulta trabalhista?',
    schedulingQuestion: 'Tem horário para consulta online essa semana?',
    menuResetPhrase: 'voltar ao menu',
    expectedWelcomeSignals: ['advogado', 'atendimento', 'area', 'ajudar', 'consulta'],
    expectedServiceSignals: ['trabalhista', 'civil', 'empresarial', 'consulta'],
    expectedPurchaseSignals: ['consulta', 'trabalhista', 'R$300', 'pagamento', 'agendar'],
    expectedSchedulingSignals: ['horario', 'online', 'semana', 'disponivel', 'agenda'],
    hasScheduling: true,
    hasCommerce: false,
  },
  {
    config: {
      businessType: 'CONSULTING',
      label: 'Consultoria & SaaS',
      description: 'Consultoria em marketing digital e automação. Planos mensais com gestão de tráfego, social media e CRM.',
      services: 'Plano Starter R$997/mês, Plano Pro R$2.497/mês, Plano Enterprise R$4.997/mês, Consultoria Avulsa R$500/hora.',
    },
    companyName: 'Digital Boost',
    welcomeQuestion: 'Oi, quero saber sobre os planos de marketing',
    serviceQuestion: 'O que está incluso no plano Pro?',
    purchaseQuestion: 'Quero contratar o plano Starter',
    schedulingQuestion: 'Podemos agendar uma reunião de apresentação?',
    menuResetPhrase: 'inicio',
    expectedWelcomeSignals: ['plano', 'marketing', 'ajudar', 'consultoria', 'servico'],
    expectedServiceSignals: ['pro', 'R$2.497', 'trafego', 'social', 'incluso'],
    expectedPurchaseSignals: ['starter', 'R$997', 'contrato', 'pagamento', 'link', 'assinar'],
    expectedSchedulingSignals: ['reuniao', 'apresentacao', 'agendar', 'horario', 'disponivel'],
    hasScheduling: true,
    hasCommerce: false,
  },
  {
    config: {
      businessType: 'AUTO',
      label: 'Auto & Mecânica',
      description: 'Oficina mecânica completa com revisão, troca de óleo, freios, suspensão e diagnóstico eletrônico.',
      services: 'Troca de Óleo R$120, Revisão Completa R$350, Alinhamento+Balanceamento R$150, Diagnóstico R$80, Pastilha Freio R$200.',
    },
    companyName: 'Auto Center Express',
    welcomeQuestion: 'Oi, meu carro está com um barulho estranho',
    serviceQuestion: 'Vocês fazem diagnóstico eletrônico?',
    purchaseQuestion: 'Quanto custa uma revisão completa?',
    schedulingQuestion: 'Tem horário para levar o carro amanhã?',
    menuResetPhrase: 'voltar',
    expectedWelcomeSignals: ['carro', 'servico', 'ajudar', 'orcamento', 'oficina', 'diagnostico'],
    expectedServiceSignals: ['diagnostico', 'eletronico', 'R$80', 'revisao', 'servico'],
    expectedPurchaseSignals: ['revisao', 'completa', 'R$350', 'orcamento', 'agendar', 'pagamento'],
    expectedSchedulingSignals: ['horario', 'amanha', 'disponivel', 'levar', 'agenda'],
    hasScheduling: true,
    hasCommerce: false,
  },
  {
    config: {
      businessType: 'TRAVEL',
      label: 'Turismo & Viagens',
      description: 'Agência de viagens com pacotes nacionais e internacionais. Passagens, hospedagem e passeios.',
      services: 'Pacote Nordeste 7 dias R$2.500, Pacote Europa 15 dias R$12.000, Passagem SP-RJ R$350, Transfer Aeroporto R$120.',
    },
    companyName: 'Viaje Mais Turismo',
    welcomeQuestion: 'Olá, quero planejar uma viagem',
    serviceQuestion: 'Quais pacotes vocês tem para o nordeste?',
    purchaseQuestion: 'Quero fechar o pacote nordeste de 7 dias para 2 pessoas',
    schedulingQuestion: 'Tem disponibilidade para março?',
    menuResetPhrase: 'menu',
    expectedWelcomeSignals: ['viagem', 'destino', 'pacote', 'ajudar', 'planejar'],
    expectedServiceSignals: ['nordeste', '7 dias', 'R$2.500', 'pacote', 'incluso'],
    expectedPurchaseSignals: ['nordeste', 'R$2.500', '2 pessoas', 'reserva', 'pagamento', 'link', 'humano', 'atendente', 'encaminhando'],
    expectedSchedulingSignals: ['marco', 'disponibilidade', 'data', 'periodo'],
    hasScheduling: false,
    hasCommerce: false,
  },
];
